apiVersion: v1
kind: Service
metadata:
  name: ddk-time-synchronizer-lb

spec:
  type: LoadBalancer
  selector:
    app: ddk-time-synchronizer
  ports:
    - name: frontend
      protocol: TCP
      port: 7070
      targetPort: 7070
