apiVersion: v1
kind: Service
metadata:
  name: ddkdebugger-frontend-lb

spec:
  type: LoadBalancer
  selector:
    app: ddkdebugger
  ports:
    - name: frontend
      protocol: TCP
      port: 4700
      targetPort: 4700
    - name: backend
      protocol: TCP
      port: 4701
      targetPort: 4701
  externalIPs:
    - 192.168.50.241
